### ISSUE TITLE
Sling TV No Longer Works in 21.4.4

### ISSUE THREAD

**Issue by eracknaphobia** [peak3d/inputstream.adaptive#1528]
## Bug report
Sling TV plays mpd drm content fine in Nexus version 20.3.18 but cannot in Omega 21.4.4
This effects all platforms

### Describe the bug
Playback fails with 404s when inputstream tries to download the .m4s files

Please check my issue for more info, including logs
https://github.com/eracknaphobia/plugin.video.slingtv/issues/6#issuecomment-2050759943

**Comment by CastagnaIT** [comment]
its possible that its only a wrong number that i have just fixed
please test with this build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1529/3/artifacts

**Comment by eracknaphobia** [comment]
Thanks for the quick response! 

I tested the build and it did fix half of the channels but some are still failing with the 404 not found. Below is the log snippet of failed playback and I've attached the mpd file.

[spanning_ads.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/14957875/spanning_ads.mpd.txt)


```
2024-04-12 06:55:40.296 T:170128   error <general>: AddOnLog: inputstream.adaptive: Download failed, no data: http://p-cdn1-805-cg14-linear-cbd46b77.movetv.com/clipslist/1640/20240412T090000Z/20240412T110000Z/spanning_ads.mpd
2024-04-12 06:55:40.404 T:45836 warning <general>: AddOnLog: inputstream.adaptive: [AS-1] Segment download failed, attempt 8...
2024-04-12 06:55:40.404 T:45836   debug <general>: CurlFile::XFILE::CCurlFile::Open - <http://p-cdn1-805-cg14-linear-cbd46b77.movetv.com/15805/live/MST3K/29c2ba22f8ad11ee90e50025b5471111/audio/stereo/192/00000d25.m4s>
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - TEXT: RESOLVE p-cdn1-805-cg14-linear-cbd46b77.movetv.com:80 is - old addresses discarded!
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - TEXT: Added p-cdn1-805-cg14-linear-cbd46b77.movetv.com:80:23.62.230.89 to DNS cache
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - TEXT: Found bundle for host p-cdn1-805-cg14-linear-cbd46b77.movetv.com: 0x18b51e961f0 [serially]
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - TEXT: Can not multiplex, even if we wanted to!
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - TEXT: Re-using existing connection! (#0) with host p-cdn1-805-cg14-linear-cbd46b77.movetv.com
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - TEXT: Connected to p-cdn1-805-cg14-linear-cbd46b77.movetv.com (23.62.230.89) port 80 (#0)
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - HEADER_OUT: GET /15805/live/MST3K/29c2ba22f8ad11ee90e50025b5471111/audio/stereo/192/00000d25.m4s HTTP/1.1
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - HEADER_OUT: Host: p-cdn1-805-cg14-linear-cbd46b77.movetv.com
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - HEADER_OUT: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - HEADER_OUT: Accept: */*
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - HEADER_OUT: Accept-Encoding: gzip, deflate
2024-04-12 06:55:40.405 T:45836   debug <general>: Curl::Debug - HEADER_OUT: Accept-Charset: UTF-8,*;q=0.8
2024-04-12 06:55:40.445 T:45836   debug <general>: Curl::Debug - TEXT: Mark bundle as not supporting multiuse
2024-04-12 06:55:40.445 T:45836   debug <general>: Curl::Debug - HEADER_IN: HTTP/1.1 404 Not Found
2024-04-12 06:55:40.446 T:45836   debug <general>: Curl::Debug - HEADER_IN: Cache-Control: max-age=2
2024-04-12 06:55:40.446 T:45836   debug <general>: Curl::Debug - HEADER_IN: Content-Length: 177
```

EDIT:
I tried the channels again and they work now. When I first tried it was towards the end of the hour so many shows were ending. I tried after the hour changed and now they work.
