### ISSUE TITLE
Wrong .ts url

### ISSUE THREAD

**Issue by c0de34fun** [peak3d/inputstream.adaptive#153]
Hi, i have problem with hls stream.
Flow tested with chrome urls is:

https://neuclnlds23lon.akamaized.net/nlds/eleven2/elevensports_pl_pl/as/live/elevensports_pl_pl_hd_pc.m3u8?h=2099b6efc3382892f08a100a8ce9ec21.1527863958220&hdnea=exp=1527864018~acl=/*~hmac=8DBE9D0AD84BF6A324FA9C361D987182F5D038F20DDF78BDB8B171DE43E2CE3B&nltid=elevensportspl&nltdt=0&uid=927133

`HTTP/1.1 200 OK
Set-Cookie: ; path=/; domain=neuclnlds23lon.akamaized.net;
Set-Cookie: nlqptid=h=2099b6efc3382892f08a100a8ce9ec21.1527863958220&hdnea=exp=1527864018~acl=/*~hmac=8DBE9D0AD84BF6A324FA9C361D987182F5D038F20DDF78BDB8B171DE43E2CE3B&nltid=elevensportspl&nltdt=0&uid=927133; path=/; domain=neuclnlds23lon.akamaized.net
X-Powered-By: ARR/3.0
Akamai-Mon-Iucid-Del: 708590
Access-Control-Allow-Origin: https://www.elevensports.pl
Access-Control-Allow-Credentials: true
Vary: Accept-Encoding
Content-Encoding: gzip
Cache-Control: max-age=52
Expires: Fri, 01 Jun 2018 14:40:10 GMT
Date: Fri, 01 Jun 2018 14:39:18 GMT
Content-Length: 245
Content-Type: application/x-mpegURL
Connection: keep-alive

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=800000
elevensports_pl_pl_hd_800_pc.m3u8?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=400000
elevensports_pl_pl_hd_400_pc.m3u8?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1200000
elevensports_pl_pl_hd_1200_pc.m3u8?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1600000
elevensports_pl_pl_hd_1600_pc.m3u8?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3000000
elevensports_pl_pl_hd_3000_pc.m3u8?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4500000
elevensports_pl_pl_hd_4500_pc.m3u8?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6000000
elevensports_pl_pl_hd_6000_pc.m3u8?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
`

https://neuclnlds23lon.akamaized.net/nlds/eleven2/elevensports_pl_pl/as/live/elevensports_pl_pl_hd_6000_pc.m3u8?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428

`HTTP/1.1 200 OK
Set-Cookie: ; path=/; domain=neuclnlds23lon.akamaized.net;
Set-Cookie: nlqptid=hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428; path=/; domain=neuclnlds23lon.akamaized.net
X-Powered-By: ARR/3.0
Akamai-Mon-Iucid-Del: 708590
Access-Control-Allow-Origin: https://www.elevensports.pl
Access-Control-Allow-Credentials: true
Vary: Accept-Encoding
Content-Encoding: gzip
Cache-Control: max-age=3
Expires: Fri, 01 Jun 2018 14:39:22 GMT
Date: Fri, 01 Jun 2018 14:39:19 GMT
Content-Length: 279
Content-Type: application/x-mpegURL
Connection: keep-alive

#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:3642187
#EXT-X-KEY:METHOD=AES-128,URI="elevensports_pl_pl_hd_6000/20180601140000.m3u8.key?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428"
#EXTINF:10,
elevensports_pl_pl_hd_6000_20180601143740.ts?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXTINF:10,
elevensports_pl_pl_hd_6000_20180601143750.ts?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXTINF:10,
elevensports_pl_pl_hd_6000_20180601143800.ts?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXTINF:10,
elevensports_pl_pl_hd_6000_20180601143810.ts?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXTINF:10,
elevensports_pl_pl_hd_6000_20180601143820.ts?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
#EXTINF:10,
elevensports_pl_pl_hd_6000_20180601143830.ts?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428
`

https://neuclnlds23lon.akamaized.net/nlds/eleven2/elevensports_pl_pl/as/live/elevensports_pl_pl_hd_6000_20180601143820.ts?hdntl=exp=1527950358~acl=/*~data=hdntl~hmac=75bb0bb2c10db217799950cb887475b72f4ebe0e0ddb77ea94af5e6b838d7428

But inputstream gives me: 

`16:39:46.077 T:123145543315456   DEBUG: AddOnLog: InputStream Adaptive: Selecting stream with conditions: w: 1054, h: 761, bw: 3600000
16:39:46.078 T:123145543315456   DEBUG: CurlFile::Open(0x7fb59796ca90) https://neuclnlds23lon.akamaized.net/nlds/eleven2/elevensports_pl_pl/as/live/elevensports_pl_pl_hd_3000_pc.m3u8?hdntl=exp=1527950386~acl=/*~data=hdntl~hmac=2a6d03635437fd7c68534c86052462d6e3250c512b349534550128eb64bdf203
16:39:46.085 T:140735718200192   DEBUG: ------ Window Init (DialogBusy.xml) ------
16:39:46.085 T:140735718200192   DEBUG: Window DialogBusy.xml was already loaded
16:39:46.085 T:140735718200192   DEBUG: Alloc resources: 0.03ms
16:39:46.232 T:123145543315456   DEBUG: AddOnLog: InputStream Adaptive: Download https://neuclnlds23lon.akamaized.net/nlds/eleven2/elevensports_pl_pl/as/live/elevensports_pl_pl_hd_3000_pc.m3u8?hdntl=exp=1527950386~acl=/*~data=hdntl~hmac=2a6d03635437fd7c68534c86052462d6e3250c512b349534550128eb64bdf203 finished
16:39:46.232 T:123145543852032   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
16:39:46.232 T:123145543852032   DEBUG: CurlFile::Open(0x7fb59823d400) https://neuclnlds23lon.akamaized.net/nlds/eleven2/elevensports_pl_pl/as/live/elevensports_pl_pl_hd_3000_pc.m3u8?hdntl=exp=1527950386~acl=/elevensports_pl_pl_hd_3000_20180601143850.ts?hdntl=exp=1527950386~acl=/*~data=hdntl~hmac=2a6d03635437fd7c68534c86052462d6e3250c512b349534550128eb64bdf203
16:39:46.249 T:123145543852032   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403`

I belive that .ts url is wrong:

https://neuclnlds23lon.akamaized.net/nlds/eleven2/elevensports_pl_pl/as/live/elevensports_pl_pl_hd_3000_pc.m3u8?hdntl=exp=1527950386~acl=/elevensports_pl_pl_hd_3000_20180601143850.ts?hdntl=exp=1527950386~acl=/*~data=hdntl~hmac=2a6d03635437fd7c68534c86052462d6e3250c512b349534550128eb64bdf203

How can i fix this ?

**Comment by JinRonin** [comment]
Kodi update to the latest nightly should fix it for you.

**Comment by c0de34fun** [comment]
Unfortunetly, on fresh installation kodi kodi-20180601-7831ed96-master-x86_64 (macosx) problem still exist:

09:44:28.811 T:123145335353344   DEBUG: AddOnLog: InputStream Adaptive: OpenStream(1)
09:44:28.812 T:123145335353344   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
09:44:28.812 T:123145335353344   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
09:44:28.812 T:123145335353344   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
09:44:28.812 T:123145335353344   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
09:44:28.813 T:123145335353344   DEBUG: AddOnLog: InputStream Adaptive: Selecting stream with conditions: w: 720, h: 480, bw: 3600000
09:44:28.813 T:123145335353344   DEBUG: CurlFile::Open(0x7f898b754330) https://neuclnlds50lon.akamaized.net/nlds/eleven2/eleven_pl_pl/as/live/eleven_pl_pl_hd_3000_pc.m3u8?hdntl=exp=1528011868~acl=/*~data=hdntl~hmac=566eabe82fba6e7e7df8ac6aaf3d42c9fbe30d717718ee4fb2e28779f979f9d7
09:44:28.963 T:123145335353344   DEBUG: AddOnLog: InputStream Adaptive: Download https://neuclnlds50lon.akamaized.net/nlds/eleven2/eleven_pl_pl/as/live/eleven_pl_pl_hd_3000_pc.m3u8?hdntl=exp=1528011868~acl=/*~data=hdntl~hmac=566eabe82fba6e7e7df8ac6aaf3d42c9fbe30d717718ee4fb2e28779f979f9d7 finished
09:44:28.964 T:123145336426496   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
09:44:28.964 T:123145336426496   DEBUG: CurlFile::Open(0x7f898cb11b00) https://neuclnlds50lon.akamaized.net/nlds/eleven2/eleven_pl_pl/as/live/eleven_pl_pl_hd_3000_pc.m3u8?hdntl=exp=1528011868~acl=/eleven_pl_pl_hd_3000_20180602074330.ts?hdntl=exp=1528011868~acl=/*~data=hdntl~hmac=566eabe82fba6e7e7df8ac6aaf3d42c9fbe30d717718ee4fb2e28779f979f9d7
09:44:29.053 T:123145336426496   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403  

Plugin opens:

https://neuclnlds50lon.akamaized.net/nlds/eleven2/eleven_pl_pl/as/live/eleven_pl_pl_hd_3000_pc.m3u8?hdntl=exp=1528011868~acl=/eleven_pl_pl_hd_3000_20180602074330.ts?hdntl=exp=1528011868~acl=/*~data=hdntl~hmac=566eabe82fba6e7e7df8ac6aaf3d42c9fbe30d717718ee4fb2e28779f979f9d7

And proper is:

https://neuclnlds50lon.akamaized.net/nlds/eleven2/eleven_pl_pl/as/live/eleven_pl_pl_hd_3000_20180602074330.ts?hdntl=exp=1528011868~acl=/*~data=hdntl~hmac=566eabe82fba6e7e7df8ac6aaf3d42c9fbe30d717718ee4fb2e28779f979f9d7

**Comment by JinRonin** [comment]
What version of inputstream.adaptive is installed? That's an old bug you are experiencing, which has been fixed already.

**Comment by c0de34fun** [comment]
It's  v2.2.20.

**Comment by JinRonin** [comment]
Can you please provide a full debug log then.

**Comment by JinRonin** [comment]
@peak3d 
Is it possible that its not checking the forward slash in params at quality level?

**Comment by peak3d** [comment]
I wanted to wait for a full log or at least for the master m3u8 URL (thanx for requesting)
But yes, for sure there is something wrong but faster for me if I can reproduce.

**Comment by JinRonin** [comment]
He has listed all urls with content in first post (including master - first link).

**Comment by peak3d** [comment]
Thax both for information:

https://github.com/peak3d/inputstream.adaptive/commit/02b31973a0c1ab75166dfb281d700b941966c8ba

should fix the issue

**Comment by c0de34fun** [comment]
I tested it, and now it works perfectly. Thank you.
