### ISSUE TITLE
Inputstream.Adaptive error updating 2.5.5 Kodi 19

### ISSUE THREAD

**Issue by orfeous1** [peak3d/inputstream.adaptive#419]
Attaching debug log.
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/4472000/kodi.log)

Inputstream.Adaptive 2.5.4 works great though, but cant update to 2.5.5 it seems.
Never been any issues with Kodi 19 and 2.5.4.

**Comment by glennguy** [comment]
Update your Kodi nightly and it will work

**Comment by HeresJonny** [comment]
2.5.5. is marked as incompatible in the last few nightlies and now other add-ons that depend on it also fail to update, like PVR IPTV Simple.

**Comment by gd71** [comment]
Hello,
indeed at least for me on ubuntu 19.10 eoan amd64
latest nightly does not help.
trying to force addon activation gives
```
ERROR <general>: Add-on 'InputStream Adaptive' is using an incompatible API version for type 'Inputstream'. Kodi API min version = '2.2.0/2.2.0', add-on API version '2.1.0/2.1.0'
```

**Comment by gd71** [comment]
looks like we shall wait for #420

**Comment by orfeous1** [comment]
Yeah, i guess we will. Lots of issues right now.

**Comment by orfeous1** [comment]
No temporary fixes i guess?

**Comment by gd71** [comment]
fixed with last release for me

**Comment by orfeous1** [comment]
Ah, okey :)
Still broken for me.

2020-04-26 10:52:59.702 T:5996    DEBUG <general>: CAddonInstaller: installing 'inputstream.adaptive' version '2.5.5' from repository 'repository.xbmc.org'
2020-04-26 10:52:59.704 T:8992    DEBUG <general>: CAddonInstallJob[inputstream.adaptive]: requires kodi.binary.instance.inputstream version 2.1.0 which is not available
2020-04-26 10:52:59.704 T:8992    ERROR <general>: CAddonInstallJob[inputstream.adaptive]: Beroendet för kodi.binary.instance.inputstream version 2.1.0 kunde inte tillfredsställs.

**Comment by HeresJonny** [comment]
The release in the Kodi repository fails because it is not marked as "matrix" and thus fails to install because of missing dependencies. The releases in this repository are not really releases, just uncompiled source code in zips. Problem persists.

**Comment by orfeous1** [comment]
I got it working today, i needed to delete the inputstream.adaptive folder. Then it worked installing from scratch from the repository. When i did not had the folder deleted Kodi couldnt find any updates. Could not reinstall it either or activate it.
Try my solution. Delete the folder from Kodi Addon.. and install it from scratch inside Kodi Addon..

**Comment by gd71** [comment]
In my ubuntu box, I subscribed to the nightly repository
https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly
Then notification and update went fine
