### ISSUE TITLE
Inputstream.Adaptive not compatible with latest Kodi Matrix v19

### ISSUE THREAD

**Issue by orfeous1** [peak3d/inputstream.adaptive#537]
Having issues with Inputstream.Adaptive and latest Kodi Matrix v19 dev 20201020.
Not compatible with Kodi the notice says when i try to activate the addon.

Seems that API has changed.
**"2020-10-22 01:17:34.039 T:13268   ERROR <general>: Add-on 'InputStream Adaptive' is using an incompatible API version for type 'Inputstream'. Kodi API min version = '2.3.4/2.3.4', add-on API version '2.3.1/2.3.1'
2020-10-22 01:17:34.039 T:13268   ERROR <general>: IAddonInstanceHandler::ADDON::IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation**"

Attaching Kodi.log
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/5418941/kodi.log)

**Comment by basilgello** [comment]
The trunk builds fine against kodi 2020-10-15 but
```shell
"/build/kodi-inputstream-adaptive-2.6.0+git20201020.b51c22af/obj-x86_64-linux-gnu/Test_DashTree" "/build/kodi-inputstream-adaptive-2.6.0+git20201020.b51c22af/src/parser/testfiles/6play.mpd"
```

exits with error 255 and test failure halts Debian packaging process. I will fix and PR it closing the issue.

**Comment by clinton-hall** [comment]
How would I go about getting this latest version in Ubuntu?
Using `ppa:team-xbmc/xbmc-nightly`

`kodi-inputstream-adaptive is already the newest version (2.6.0-1~bionic).`
but this version is not compatible with kodi (2:19.0+git20201025.0300-c413111b87-0bionic)

**Comment by clinton-hall** [comment]
Ok, the answer was simple. Wait another 8 hours and this had now been updated in the xbmc-nightly ppa!
`kodi-inputstream-adaptive (2.6.1-1~bionic)` is installed and working.

**Comment by orfeous1** [comment]
My issue is now solved! Works with Inputstream.Adaptive 2.6.1

**Comment by orfeous1** [comment]
New issue!
Updated Kodi to KodiSetup-20201117
Now Kodi disables InputStream.Adaptive.
Debug log only tells me that Inputstream.Adaptive is not compatible with Kodi.

Tried to activate Inputstream.Adaptive addon via Kodis addon-manager.. but got the error about its not compatible with Kodi.

Attaching log of Kodi.
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/5563415/kodi.log)

**Comment by orfeous1** [comment]
Fixed with Kodi 20201123-f1ea0e47 and Inputstream.Adaptive 2.6.6
Thank you!

**Comment by mmtechnodrone** [comment]
> Fixed with Kodi 20201123-f1ea0e47 and Inputstream.Adaptive 2.6.6
> Thank you!

I compiled Kodi from master today. Inputstream Adaptive compiles and will enable but does not play content.

**Comment by mmtechnodrone** [comment]
Updates now have fixed it for Netflix and Amazon. Sling still doesn't work, but it's probably a bug in the addon.

**Comment by CharlesCanlom** [comment]
Having issues installing 19.0.0 on my Kodi 19.3 install on android 9
